version: '3.8'

services:
  frontend:
    container_name: salesManagementFrontend
    build:
      context: ./sales_management_front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}

  backend:
#    image: openjdk:17
    build:
      context: ./sales_management_api/jar
      dockerfile: Dockerfile
    container_name: salesManagementBackend
#    volumes:
#      - /home/ubuntu/sales_management/sales_management_api/jar:/app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_USERNAME=${MYSQL_ROOT_USERNAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - FILE_UPLOAD_DIR=${FILE_UPLOAD_DIR}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  db:
    image: mysql:8.4.0
    container_name: salesManagementDB
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: salesManagement
    ports:
      - "3306:3306"

  redis:
    image: redis:7.2-alpine
    container_name: salesManagementRedis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: redis-server --requirepass $REDIS_PASSWORD

  nginx:
    image: nginx:alpine
    container_name: salesManagementProxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./sales_management_front/build:/usr/share/nginx/html
    env_file:
      - .env

volumes:
  redis-data: